In [863]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [864]:
import numpy as np

In [865]:
np.__version__

'1.19.5'

In [866]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Matrix or 2D Array


In [867]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [868]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [869]:
a[2:5]

array([3, 4, 5])

In [870]:
L = [1,2,3,4,5,6,7]
L[0]

1

In [871]:
L[2:5]

[3, 4, 5]

In [872]:
a[ :6 ]

array([1, 2, 3, 4, 5, 6])

In [873]:
L[:5]

[1, 2, 3, 4, 5]

In [874]:
a[ 3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [875]:
L[ 3:]

[4, 5, 6, 7]

In [876]:
a[ -3]

8

In [877]:
a[ -2]

9

In [878]:
a[ -1]

10

In [879]:
a[ 2: -3]

array([3, 4, 5, 6, 7])

In [880]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [881]:
a[-5:-1]

array([6, 7, 8, 9])

In [882]:
np.size(a)

10

In [883]:
np.shape(a)

(10,)

In [884]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [885]:
a[a[2]]

4

In [886]:
L[L[2]]

4

In [887]:
L.reverse()
L

[7, 6, 5, 4, 3, 2, 1]

In [888]:
sorted(a, reverse=True)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [889]:
np.shape(a)


(10,)

In [890]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [891]:
L= [[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [892]:
L[0][0]

1

In [893]:
L[0]

[1, 2, 3]

In [894]:
a.shape

(10,)

In [895]:
a.ndim

1

In [896]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [897]:
a = np.array(np_mix_matrix[:,1],dtype = int)
a

array([2, 4, 6])

In [898]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [899]:
a = np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [900]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [901]:
b = np.ones((10,10))
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [902]:
b = np.ones((5,5))*8
b

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [903]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [904]:
b*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [905]:
np.matmul(b,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [906]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [907]:
np.empty([5,5])

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [908]:
np.empty([20,20])

array([[ 6.90554183e-310,  4.66326163e-310,  0.00000000e+000,
         0.00000000e+000, -2.04991607e+204,  6.90554161e-310,
         4.66325858e-310, -4.88671775e+033,  6.90554161e-310,
         4.66325858e-310,  2.33280770e-304,  6.90554161e-310,
         4.66325858e-310,  1.89373941e-134,  6.90554161e-310,
         4.66325857e-310, -1.78010059e+238,  6.90554161e-310,
         4.66325858e-310, -1.16414628e+125],
       [ 6.90554161e-310,  4.66325858e-310,  1.89589668e-048,
         6.90554161e-310,  4.66325857e-310,  1.71214005e+232,
         6.90554161e-310,  4.66325858e-310,  7.77165354e-042,
         6.90554161e-310,  4.66325857e-310, -5.51801886e+239,
         6.90554161e-310,  4.66325858e-310, -1.00364069e-274,
         6.90554161e-310,  4.66325858e-310, -3.71097854e+155,
         6.90554161e-310,  4.66325858e-310],
       [ 2.25706795e+179,  6.90554161e-310,  4.66325857e-310,
         3.17964479e+028,  6.90554161e-310,  4.66325858e-310,
         2.73919514e-171,  6.90554161e-310

In [909]:
np.random.rand()

0.3098261818029643

เลขที่สุ่มออกมาอยู่ช่วงระหว่าง 0-1

In [910]:
np.random.randint(5)

4

In [911]:
[np.random.randint(5) for item in range(10)]

[2, 3, 2, 4, 4, 1, 2, 1, 4, 4]

In [912]:
np.random.rand(5,5)

array([[0.52089915, 0.30132826, 0.42139543, 0.52918925, 0.28296885],
       [0.8901058 , 0.37174611, 0.78481101, 0.12284831, 0.87397862],
       [0.54246661, 0.29799089, 0.48323179, 0.34880516, 0.0248764 ],
       [0.82050986, 0.57079162, 0.89263719, 0.97850527, 0.36936812],
       [0.85182988, 0.6849768 , 0.50232906, 0.85457345, 0.8217575 ]])

In [913]:
np.round(np.random.rand(5,5))

array([[1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [914]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([4, 3, 9, 9, 9])

In [915]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([5, 8, 9, 3, 4])

สุ่มแบบไม่ซ้ำกัน

In [916]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       ...,
       [1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.]])

In [917]:
idx_choose = np.random.choice(1000,100, replace = False)
idx_choose

array([385, 321, 315, 870, 294, 709, 582, 231, 462, 626, 342, 806, 391,
       386, 286, 103, 331, 963, 119, 264, 793, 607, 957, 371, 655,  22,
       578,  34, 653, 421, 133, 344, 721,  24, 141, 249, 724, 813, 209,
       233, 979, 484, 152, 980,  54, 611,  82, 871, 545, 218, 853, 901,
       130, 225, 927, 118, 176, 812, 760, 530, 145, 186, 689, 466, 564,
       167, 635, 298,   8, 474, 252, 824, 675, 887, 520, 128, 532, 819,
       729, 776, 521, 571, 458, 257, 969, 634, 790, 477, 531, 938, 372,
        55, 534, 936, 171, 882, 834, 397, 216, 937])

In [918]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 1.],
       [1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1.],
       [0., 0.

In [919]:
#EX 2
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np_matrix[:,4])
np_matrix

array([[0.00323081, 0.77406918, 0.95915835, 0.5369957 , 0.        ],
       [0.28940303, 0.35146779, 0.12181821, 0.55079005, 1.        ],
       [0.68116699, 0.88347377, 0.78521534, 0.27893647, 1.        ],
       [0.28199371, 0.95365477, 0.38746771, 0.92472683, 0.        ],
       [0.17442625, 0.54519419, 0.52924254, 0.24162302, 0.        ],
       [0.35758491, 0.42437605, 0.34765143, 0.01418086, 0.        ],
       [0.03395896, 0.55152149, 0.25047343, 0.92537968, 0.        ],
       [0.52839546, 0.47150156, 0.65095633, 0.44918979, 1.        ],
       [0.59396729, 0.35686555, 0.1875082 , 0.75467177, 1.        ],
       [0.87182707, 0.37524142, 0.20861372, 0.02621585, 1.        ]])

EX.2

In [920]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 1, 10,  2,  4,  8],
       [ 9,  4, 10,  3,  8],
       [ 7,  4,  1,  3,  7],
       [ 3,  3,  7,  3,  2],
       [ 8,  2,  6,  5,  4]])

In [921]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 2), (3, 4), (4, 1)]

เช็คหาข้อมูล

In [922]:
i

array([0, 3, 4])

In [923]:
j

array([2, 4, 1])

In [924]:
np_matrix = np.random.randint(5,size = (5,5))
np_matrix

array([[4, 1, 2, 0, 4],
       [3, 0, 4, 2, 4],
       [0, 0, 1, 1, 2],
       [2, 4, 4, 2, 4],
       [3, 1, 3, 3, 4]])

In [925]:
#Ex 3
idx = [1,2,3,4,5]
np_matrix[idx[:5-1],:]



array([[3, 0, 4, 2, 4],
       [0, 0, 1, 1, 2],
       [2, 4, 4, 2, 4],
       [3, 1, 3, 3, 4]])

EX 3

In [926]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

In [927]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[2, 2, 3, 6, 1],
       [3, 9, 3, 9, 6],
       [4, 9, 7, 8, 0],
       [0, 0, 2, 9, 2],
       [3, 5, 0, 6, 1]])

In [928]:
rng = np.random.RandomState(0)
rng.randint(5)

4

In [929]:
rng = np.random.RandomState(0)
[np.round(rng.rand()*10) for item in range(10)]

[5.0, 7.0, 6.0, 5.0, 4.0, 6.0, 4.0, 9.0, 10.0, 4.0]

In [930]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [931]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[0, 1, 1],
       [2, 0, 0],
       [0, 2, 2],
       [0, 1, 1],
       [0, 0, 1]])

In [932]:
a = np_matrix == 2
a

array([[False, False, False],
       [ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [933]:
np_matrix[a] = 99
np_matrix

array([[ 0,  1,  1],
       [99,  0,  0],
       [ 0, 99, 99],
       [ 0,  1,  1],
       [ 0,  0,  1]])

In [934]:
#EX.4
np_matrix = np.random.randint(10,size = (10,5))
np_matrix 

array([[6, 6, 3, 7, 1],
       [5, 6, 8, 7, 2],
       [7, 9, 1, 7, 4],
       [0, 7, 1, 6, 0],
       [6, 2, 2, 8, 3],
       [6, 9, 0, 1, 5],
       [6, 8, 6, 4, 5],
       [0, 0, 8, 9, 3],
       [8, 9, 7, 8, 4],
       [2, 8, 4, 6, 3]])

In [935]:
label_vector = np.random.randint(2,size = 10)
label_vector

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1])

In [936]:
train_data = np_matrix[np.where(label_vector == 0)]
train_data

array([[6, 6, 3, 7, 1],
       [0, 7, 1, 6, 0],
       [6, 8, 6, 4, 5],
       [0, 0, 8, 9, 3],
       [8, 9, 7, 8, 4]])

In [937]:
test_data = np_matrix[np.where(label_vector == 1)]
test_data

array([[5, 6, 8, 7, 2],
       [7, 9, 1, 7, 4],
       [6, 2, 2, 8, 3],
       [6, 9, 0, 1, 5],
       [2, 8, 4, 6, 3]])